#!/bin/bash

set -e -u -o pipefail

# This script implements [jenga root], so people can conveniently
# find the root from within jenga.

if [ $# -ge 1 ] && [ "$1" = "root" ]; then
    if [ $# -ne 1 ]; then
        echo >&2 "Too many arguments passed to [$0 root]"
        exit 1
    fi
    # keep going
else
    exit 127 # pretend jenga doesn't exist
fi

# taken from jenga/scripts/version-dispatch.sh until STOP

root=""
dir="$(pwd)"
if [ -f "$dir/jenga.conf" ]; then root="$dir"; fi
if [ -f "$dir/jengaroot.ml" ]; then root="$dir"; fi
while [ "$dir" != "/" -a "$root" = "" ] ; do
    dir="$(dirname "$dir")"
    if [ -f "$dir/jenga.conf" ]; then root="$dir"; fi
    if [ -f "$dir/jengaroot.ml" ]; then root="$dir"; fi
done

if [ "$root" = "" ]; then
    echo >&2 "$(basename $0): No 'jenga.conf' in start-dir or any ancestor dir"
    exit 1
fi

# STOP

echo "$root"
