#!/bin/bash

# man ranlib...
#
#       The GNU ranlib program is another form of GNU ar; running ranlib is completely equivalent to executing ar -s.

# man ar...
#
#       D   Operate in deterministic mode.  When adding files and the archive index use zero for UIDs, GIDs, timestamps, and use consistent file modes for all files.  When
#           this option is used, if ar is used with identical options and identical input files, multiple runs will create identical output files regardless of the input
#           files’ owners, groups, file modes, or modification times.

# By having the directory which contains this script early in the
# path, we intercept calls made to ranlib from the ocaml compiler
# running is "-a" (archive) mode.  Deterministic output from ranlib
# avoids needlessly rebuilding every .exe which links with the
# library, just in case the .a is identically-regenerated, for example
# if the compile command is rerun after the .a or .cmxa is removed.

case $(uname) in
    Darwin)
        prog=gar
        ;;
    *)
        prog=/usr/bin/ar
        ;;
esac

$prog -Ds "$@"
